# Generated by Django 2.2.2 on 2019-06-16 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id_cliente', models.AutoField(default=0, editable=False, primary_key=True, serialize=False)),
                ('nome_cliente', models.CharField(default='', max_length=100)),
                ('rg_cliente', models.CharField(default='', max_length=7)),
                ('endereco_cliente', models.CharField(default='', max_length=50)),
                ('telefone_cliente', models.CharField(default='', max_length=11)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Funcionarios',
            fields=[
                ('id_funcionario', models.AutoField(default=0, editable=False, primary_key=True, serialize=False)),
                ('nome_funcionario', models.CharField(default='', max_length=100)),
                ('rg_funcionario', models.CharField(default='', max_length=7)),
                ('endereco_funcionario', models.CharField(default='', max_length=50)),
                ('telefone_funcionario', models.CharField(default='', max_length=11)),
                ('data_admissao', models.DateTimeField(default=0)),
                ('salario', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
            options={
                'verbose_name': 'Funcionário',
                'verbose_name_plural': 'Funcionários',
            },
        ),
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id_produto', models.IntegerField(default=0, editable=False, primary_key=True, serialize=False)),
                ('nome_produto', models.CharField(default='', max_length=100)),
                ('descricao', models.TextField(default='')),
                ('quantidade', models.IntegerField(default=0)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
            },
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id_venda', models.IntegerField(default=0, editable=False, primary_key=True, serialize=False)),
                ('nome_venda', models.CharField(default='', max_length=100)),
                ('data_venda', models.DateTimeField(auto_now_add=True)),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.Clientes')),
                ('id_funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.Funcionarios')),
                ('id_produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.Produtos')),
            ],
            options={
                'verbose_name': 'Venda',
                'verbose_name_plural': 'Vendas',
            },
        ),
    ]
