# Generated by Django 2.2.2 on 2019-06-16 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venda',
            old_name='id_cliente',
            new_name='cliente',
        ),
        migrations.RenameField(
            model_name='venda',
            old_name='id_funcionario',
            new_name='funcionario',
        ),
        migrations.RenameField(
            model_name='venda',
            old_name='id_produto',
            new_name='produto',
        ),
        migrations.AlterField(
            model_name='clientes',
            name='id_cliente',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='funcionarios',
            name='id_funcionario',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='id_produto',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='venda',
            name='id_venda',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
