# Generated by Django 2.2.2 on 2019-06-18 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtos',
            name='quantidade_produto',
            field=models.IntegerField(),
        ),
    ]
