# Generated by Django 2.2.2 on 2019-06-19 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_remove_vendas_quantidade_venda'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendas',
            name='quantidade_venda',
            field=models.IntegerField(default=0, max_length=5),
        ),
    ]
