# Generated by Django 2.2.2 on 2019-06-16 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_auto_20190616_0206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='id_cliente',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='funcionarios',
            name='id_funcionario',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='id_produto',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='venda',
            name='id_venda',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
