# Generated by Django 2.2.2 on 2019-06-18 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_auto_20190618_0407'),
    ]

    operations = [
        migrations.CreateModel(
            name='Erro',
            fields=[
                ('id_erro', models.AutoField(primary_key=True, serialize=False)),
                ('nome_relato', models.CharField(max_length=50)),
                ('descricao_erro', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='produtos',
            name='observacao',
            field=models.TextField(blank=True, default='-', null=True),
        ),
    ]
