# Generated by Django 2.2.2 on 2019-06-16 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0003_auto_20190616_0209'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendas',
            fields=[
                ('id_venda', models.AutoField(primary_key=True, serialize=False)),
                ('nome_venda', models.CharField(default='', max_length=100)),
                ('data_venda', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.Clientes')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.Funcionarios')),
            ],
            options={
                'verbose_name': 'Venda',
                'verbose_name_plural': 'Vendas',
            },
        ),
        migrations.AlterField(
            model_name='produtos',
            name='id_produto',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='Venda',
        ),
        migrations.AddField(
            model_name='vendas',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.Produtos'),
        ),
    ]
