# Generated by Django 2.2.2 on 2019-06-18 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0003_auto_20190618_1057'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='erro',
            options={'verbose_name': 'Erro', 'verbose_name_plural': 'Erros'},
        ),
    ]
