# Generated by Django 2.2.2 on 2019-06-16 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0004_auto_20190616_0407'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtos',
            name='observacao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='descricao',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='quantidade',
            field=models.IntegerField(default=10),
        ),
    ]
