# Generated by Django 2.2.2 on 2019-06-20 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0004_auto_20190620_0313'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtos',
            name='custo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Custo da C'),
        ),
    ]
