# Generated by Django 2.2.2 on 2019-06-20 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0005_produtos_custo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produtos',
            name='custo',
        ),
    ]
