# Generated by Django 2.2.2 on 2019-07-05 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0006_remove_produtos_custo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendas',
            name='nome_venda',
        ),
    ]
