# Generated by Django 2.2.2 on 2019-06-18 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0008_auto_20190618_0335'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produtos',
            old_name='quantidade',
            new_name='quantidade_produto',
        ),
        migrations.RenameField(
            model_name='produtos',
            old_name='valor',
            new_name='valor_produto',
        ),
        migrations.RemoveField(
            model_name='vendas',
            name='quantidade',
        ),
        migrations.RemoveField(
            model_name='vendas',
            name='valor_total',
        ),
    ]
